version: '3'

services:
  back:
    build: ./back
    container_name: back
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"
    volumes:
      - ./back:/back
    environment:
      - TZ=Asia/Tokyo
    restart: always
    tty: true
